name: Build
on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        gradle: [5.3.1, 5.4.1, 5.5.1, 5.6.4, 6.0.1, 6.1.1, 6.2.2, 6.3, 6.4.1]
        experimental: [false]
        include:
          - gradle: rc
            experimental: true
    runs-on: ubuntu-18.04
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v2
        id: cache-mavenize
        with:
          path: ~/.mavenize/eclipse_archive_cache
          key: ${{ runner.os }}-mavenize-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-mavenize-
      - uses: actions/cache@v2
        id: cache-gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ matrix.gradle }}
          arguments: buildAll --parallel --stacktrace --warning-mode all
