---
name: Build

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - develop
    tags:
      - "release-*.*.*"
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [11]
        gradle: [7.6.4]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Cache Eclipse
        uses: actions/cache@v4
        with:
          path: |
            ~/.mavenize/eclipse_archive_cache/*.dmg
            ~/.mavenize/eclipse_archive_cache/*.zip
            ~/.mavenize/eclipse_archive_cache/*.tar.gz
          key: mavenize-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            mavenize-${{ runner.os }}-
      - name: Setup Gradle ${{ matrix.gradle }}
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ matrix.gradle }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
      - name: Build
        run: |
          gradle buildAll --parallel --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
